# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all'
right_format = ''
continuation_prompt = '[∙](bright-black) '
scan_timeout = 30
command_timeout = 500
add_newline = true

palette = "cyberdream"

[character]
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

[palettes.cyberdream]
rosewater = "#ff5ea0"
flamingo = "#ff5ea0"
pink = "#ff5ea0"
mauve = "#ff5ef1"
red = "#ff6e5e"
maroon = "#ffbd5e"
peach = "#ffbd5e"
yellow = "#f1ff5e"
green = "#5eff6c"
teal = "#5ef1ff"
sky = "#5ef1ff"
sapphire = "#5ef1ff"
blue = "#5ea1ff"
lavender = "#bd5eff"
text = "#cad3f5"
subtext1 = "#7b8496"
subtext0 = "#7b8496"
overlay2 = "#3c4048"
overlay1 = "#3c4048"
overlay0 = "#3c4048"
surface2 = "#1e2124"
surface1 = "#1e2124"
surface0 = "#1e2124"
base = "#16181a"
mantle = "#1e2124"
crust = "#1e2124"
