k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kubernetes-admin@cluster-ns-v2
  currentCluster: cluster-ns-v2
  keepMissingClusters: false
  clusters:
    cluster-ns-v2:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - master-trainer-v3
        - default
      view:
        active: nodes
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/4q/vz8j0lpn4bv00nbd97z7pm5r0000gn/T/k9s-screens-darius
  disablePodCounting: false
